- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-ast-rES/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-b+ast+Latn+IT+AREVELA/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-b+ast/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-b+en+Latn+419/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-b+en+Latn+US/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-b+en+US+POSIX/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-b+eng+419/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-en-rUS/strings.xml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/res/values-ldrtl/strings.xml
- Handles BCP47 tags
- Removed busted layoutDirection
> [WIP] Initial support for BCP47 tags

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/apktool.yml
- brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/unknown/stored.file
- brut.j.util/src/main/java/brut/util/BrutIO.java
Java NIO doesn't allow the preservation of the compression method (STORED vs DEFLATED), so unfortunately we need to fall back to ZipEntry-based output for unknown files.
This is specifically to fix the issue discussed here: https://github.com/iBotPeaches/Apktool/issues/878
> Java NIO doesn't allow the preservation of the compression method.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResBoolValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResFileValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResIntBasedValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResIntValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResScalarValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStringValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
This makes the raw int resource values available to callers for resource types that are based on the int value read from the resource file.
The raw int available here is the same int that you'll find on TypedValue.data.
> Propagate the raw int values to callers

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkOptions.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
- brut.j.dir/src/main/java/brut/directory/AbstractDirectory.java
- brut.j.dir/src/main/java/brut/directory/Directory.java
- brut.j.dir/src/main/java/brut/directory/ZipRODirectory.java
This is the list of files (resources, assets, etc) that are stored in
the .apk uncompressed.
For apps that use AssetFileDescriptor.openFd(), the adding compression
will break the call.
Maintains support for the resourcesAreCompressed key, but no longer
records it when decompiling (it instead records resources.arsc in the
doNotCompress list).
> Adds doNotCompress list to apktool.yml

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
If we have no file extension apktool.yml's doNotCompress record for this file will look like: ''. It will cause build error. So use file name for that files.
> Fixes issue #1122

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
If I decode the framework-res.apk from the recent release of the Huawei Honor 5x I get this exception:
```
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x01040384 string/lockscreen_carrier_default, config=[DEFAULT]
at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:223)
at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
at …
```
> decoder: Extend "keep-broken-res" to also ignore duplicate resources

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
Addresses issue #1186
Reduces the time it takes to parse the Android framework by ~50%.
The synthesized name now has no leading zeroes, but this doesn't appear to matter since the numeric part of the name isn't used anywhere.
> #1186 Performance: usage of String.format in ARSCDecoder.addMissingResSpecs

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
Create fake AndroidManifest.xml file inside each installed framework file to support official aapt from Google.
This should fix such issues as https://github.com/iBotPeaches/Apktool/issues/1224
> Support for official aapt

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
When reference string is used for versionName in AndroidManifest.xml,
fetch the literal value of the referened string in the output apk.
This patch doesnt modify the original apk.
Reusing function pullValueFromStrings in ResXmlPatcher to fetch literal strings.
> Issue 1234 - Use literal value of versionName when used

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
> Skips unknown bytes if mismatch occurs after reading Configurations

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliBuilder.java
When apktool creates a DexBuilder class, it creates it without specifying a minimum api level. This causes the DexBuilder class to assume api level 20 by default. This is not ideal since in some cases, the concrete minimum api level is required.
One such case is in smali's DexWriter class which implements a workaround for a bug in Dalvik that was fixed in Android 4.2 (https://code.google.com/p/android/issues/detail?id=35304) that causes apps that call the Method.getParameterAnnotations api to crash in some cases (see bug report for more details). The workaround that smali implements is only triggered if the minimum api level is below 17 (Android 4.2). But since apktool effectively sets the minimum api level to 20, this code is never triggered causing apktool to create apk files that crash …
> Pass minimum api level to smali library

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
Some APKs' arsc has additional payload data (like TYPE 8 chunks and/or padding) in the TYPE chunk. After the ARSCDecoder read such kind of chunk, it acts erratically. Most of the time, it just stops parsing the ARSC, therefore, some resources are not decoded because they are not in the apktool's resources' spec table.
The example APKs, attached below, is from Huawei P9 Plus ROM (VIEL29C636B170). Both APK's resource are successfully decoded by aapt included in build tools v24.
[Gallery2.apk.zip](https://github.com/iBotPeaches/Apktool/files/478287/Gallery2.apk.zip)
[HwCamera2.apk.zip](https://github.com/iBotPeaches/Apktool/files/478286/HwCamera2.apk.zip)
> Skip additional payload data of TYPE chunk

- install/index.md
I don't know why bitbucket download link need a forward slash at the end, anyway I fix it.
> Fix dead links

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
Hi, 
We have discovered that the binary coded xml resource reading code is broken in th apktool. On the utf-8 coded resource files the string length was calculated from the 0 termination and the original coded value was not used. On utf-16 coded files the lengths were s improperly loaded if the length is coded in 4 bytes. 
This fix corrects the problem and allows apktool to correctly read-in lengths both on utf-8 and utf-16. 
Please review the changes and apply the patch to the master branch. 
Best regards, 
Attila Nagy
> fix of binary xml string length encoding, apktool is now supporting long resource lengths

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/Res9patchStreamDecoder.java
Original code:
https://worldwind31.arc.nasa.gov/svn/trunk/WorldWind/src/gov/nasa/worldwind/util/gdal/GDALUtils.java
/JDK-5051418
Fixes #1508
> In case of a grayscale + alpha 9patch, work-around JDK.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResResSpec.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTypeSpec.java
Basically, on import getResSpec is called multiple times and very often throws an exception. Returning null is much faster and therefore in cases where the caller does not rely on a thrown exception, it may use the new getResSpecUnsafe method.
> Making framework read in much faster

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
- brut.j.util/src/main/java/brut/util/Jar.java
Class.class.getResourceAsStream tries to load resource from root directory. This fails when apktool is built into a fat jar like Spring boot executable so that the classloader tries to load the resource from the root directory of the Spring boot jar instead of that of the bundled appktool jar.
fixes #1543
> getResourceAsStream relative based on calling class.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
> Remove .exit() falls from library code

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
The font files in the `font` folder are not encoded.  Treating them as `raw` on `decode` allows them to be properly dealt with during `build`.
Fixes #1662
> Treat fonts as raw data, fixes #1662

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
Forces decoding of AndroidManifest.xml, even if `--no-res` is set. This is useful for analysis of the manifest if resources aren't relevant, saving the step of decoding other resources, which account for a significant amount of time.
I have set it to be an advanced option, named `--force-manifest` (feel free to change this). As such:
- Setting `--force-manifest` and not setting `--no-res` does not change the previous behavior of Apktool;
- Setting `--force-manifest` and `--no-res` decodes AndroidManifest.xml, but not other resources.
If accepted, I can submit another pull request regarding `gh-pages` with documentation for this option.
> Add option to force decoding of AndroidManifest.xml

- .gitignore
- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
Hello! I'm sending this pull request on behalf of Facebook. We've been using a slightly modified APKTool internally- it would be great to get the changes incorporated back into this main open source repository.
There are two main changes:
- Added a flag for only extracting and decoding AndroidManifest.xml (without unpacking resources or sources). We have a use case where all we need are this decoded manifest and the .yml file- this makes the execution significantly faster.
- Added support for duplicate / repeated offsets (for resource entries). There are some built in assumptions in the ARSCDecoder- it assumes that offsets will always be in incrementing order, and that there will be no duplicates. These happen to be true for APK's that are built using standard android tools (aapt, aapt2), …
> Patch APKTool to allow repeated entry offsets to appear

- _includes/options-rebuild.md
Currently, the description for the --use-aapt2 argument is a copy of
another argument's description, which is wrong. This patch changes
the description to "Use the aapt2 binary instead of appt".
> Fix documentation description for --use-aapt2

- scripts/windows/apktool.bat
I added a bit of functionality to the apktool wrapper script and thought I'd share. This has several advantages compared to the base currently available:
1. No environment pollution
2. Automatic pick of the latest version, without the need to rename
3. Supports command-less calls, if the only parameter is a directory or an apk
* Supports drag & drop
* Supports double-click
* Supports "Send to" functionality
4. Pauses when ran non interactively, so the prompt doesn't automatically close
If the script finds an `apktool.jar` it's selected automatically, otherwise it looks for jar versions available in its directory with the name format `apktool_<version>.jar` and picks the latest accordingly.
With drag & drop, send-tos and calls:
* if the parameter is an apk file, the script issues the `d` …
> Enhanced Windows wrapper script

- brut.apktool/apktool-cli/build.gradle
- brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java
- build.gradle
API level now has to be specified in smaliFlexLexer constructor, won't compile otherwise.
https://github.com/JesusFreke/smali/commit/209ba3b0a6d5fc50ffbf0d2462ec195ed24204be
> build: update to smali/baksmali 2.3.4

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
This adds an additional check if the attribute namespace belongs to Android namespace, and if so we try to decode using attribute decoder.
If `decodeManifestAttr` throws an exception, we want to use the original `value`. Note that if `value.length() == 0`, then the `value` is already the empty string.
We found this issue and resolved it during the effort of de-obfuscating obfuscated APKs.
Please see Project BAOBAB for details: https://github.com/theori-io/POC2019-BAOBAB
> Fix AXML parser to handle obfuscated attribute names

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/apktool.yml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/apktool.yml
Put full file path of empty, stored files on the doNotCompress list to keep the resulting APK as close to the original as possible.
Fixes #2333.
> Fix empty uncompressed file issue 2333

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlPatcher.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableFalseChangeToTrueTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableTrueAddedTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableTrueRetainedTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-false/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-false/apktool.yml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-false/res/values/strings.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-missing/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-missing/apktool.yml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-missing/res/values/strings.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-true/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-true/apktool.yml
- brut.apktool/apktool-lib/src/test/resources/aapt2/issue2328/debuggable-true/res/values/strings.xml
Closes #2328 
- when using aapt and debug flag, we remove the 'debuggable' attribute from AndroidManifest and aapt adds it back. (see issue 1621)
- when using aapt2 and debug flag, we add and set the value of 'debuggable' attribute ourselves.
> fix the usage of debug flag (-d) when using aapt2 (issue #2328)

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
for use in scripts, it's not convenient to get an exit code 0 on
failure.
> exit code 1 if parameters are wrong

- gradle/wrapper/gradle-wrapper.properties
To build with JDK 14, we need a newer version of Gradle.
> updated gradle

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
This will cause a change that dummy attributes are now longer boolean (false). 
plurals
old:
```
<item type="plural" name="APKTOOL_DUMMY_4">false</item>
```
new:
```
<plurals name="APKTOOL_DUMMY_4" />
```
styles
old:
```
<item type="style" name="APKTOOL_DUMMY_3fe">false</item>
```
new:
```
<style name="APKTOOL_DUMMY_3fe" />
```
> fix: set dummy attributes to same type (@null)

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
> Properly handle non-framework namespaces when obfuscated

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/res/decoder/StringBlockWithSurrogatePairInUtf8Test.java
Closes #2299 
- [DEX format uses Modified UTF-8](https://source.android.com/devices/tech/dalvik/dex-format#mutf-8) which includes:
_Code points in the range U+10000 … U+10ffff are encoded as a surrogate pair, each of which is represented as a three-byte encoded value._
...
_MUTF-8 is actually closer to the (relatively less well-known) encoding CESU-8 than to UTF-8 per se._
Based in this, I suggest this change:
- If decoding fails for a UTF-8 "String block", then try to use CESU-8.
- I didn't want to always use CESU-8 because it's not clear that it is the actual decoder that should be used, but it does seem to work for the specific examples I tried.
- I wrote some unit tests for StringBlock#decodeString. I didn't add tests at a higher level, i.e., decoding an APK and verifying the …
> Use CESU-8 decoder if UTF-8 decoder fails (issue #2299)

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
When decoding an apk assembled with an app bundle, like TikTok, Apktool will raise a error:
Look at [ARSCDecoder.java#L126](https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java#L126) we can find the reason: 
``` Java
while (mHeader.type == Header.TYPE_LIBRARY) {
readLibraryType();
}
while (mHeader.type == Header.TYPE_SPEC_TYPE) {
readTableTypeSpec();
}
```
Apktool expected to read lib chunks first and then specType chunks. But in AOSP [LoadedArsc.cpp#L420](http://androidxref.com/9.0.0_r3/xref/frameworks/base/libs/androidfw/LoadedArsc.cpp#420) we can find that Google does not specify the order of the two. 
So when decoding these apks, `ResPackage readTablePackage()` just read spec types and return, left the …
> support lib/specType out-of-order reading - fix "Invalid chunk type: expected=0x00000200, got=0x00000203"

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/res/decoder/StringBlockWithSurrogatePairInUtf8Test.java
Fixes #2546
This fixes a case which wasn't handled in #2299.
* When a string can't be decoded with UTF-8, we retry the decoding with CESU-8 (done as part of #2299)
* If the bytes that can't be decoded are not at the start of the bytes range to be decoded, then the UTF-8 decoder changes the position of the ByteBuffer and the CESU-8 decoder will start decoding at the new position.
* To avoid this, we wrap the  array with a new ByteBuffer and use it with the CESU-8 decoder.
For example, before this change, when trying to decode with UTF-8 the bytes representing the following:
Good morning! 👋 Sun 🌞
The UTF-8 will read from the byte buffer partially and the CESU-8 will decode this:
👋 Sun 🌞
> Create a new ByteBuffer for decoding when retrying with CESU-8

- build.gradle
- Move ext properties into one `ext{}`
- Make JavaCompile options for all projects
- Put `gradle.startParameter.excludedTaskNames` args in set
- Use string template instead of string plus
> Optimize gradle

- index.md
When clicking on the IRC link, the channel textbox is now properly filled with the channel name, instead of the default #libera name
> Directly point to #apktool channel

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliDecoder.java
We take advantage of the fact that baksmali can determine the minimum API version needed for a given collection of opcodes and extract it, then save to mMinSdkVersion, which is only used by smali via buildSourcesSmali.
We then save that value in apktool.yml for JARs only.
This change, in addition to my previous change, allows to decompile and recompile JARs without worrying about specifying an API level via -api/--api-level.
Note: currently we only return API level from baksmali, later we can return a result object with other parameters, if ever necessary.
As an extra, added webp file extension to NO_COMPRESS_PATTERN, according to AAPT2 standards, and since it's factually never compressed as it's an already compressed format.
https://cs.android.com/android/platform/superproject/+/master:fr …
> Determine minSdkVersion with baksmali for JARs + don't compress webp

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
- brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/res/values-mcc001/strings.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values/strings.xml
fixes issue where strings.xml had an entry:
<string name="test_apktool">" <ul> <li><b>aaaaa aa aaaaa</b> – aaaaaaa aaaaaaaaaa aa aaaaaaaa aaaaaa aaaaa (aaaa) aaaa aaaaaaaaa aaaaa aa aaaaaaaaa aaaaaaa aaaa</li>\n <li><b>aaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaa</b> – aaaaaaa aaaaaaaaaa aaaaaaaaa aaaa aaaaaa aa aaaa aaaa aaaa aaaa aaaaaaa aaaaaaaaaaaaa, aaaaaa aaa aaaaaaaaaa (aaa) aaaaaaaaaaaaaaa</li>\n <li><b>aaaaaaaaaaa aaaaaa aaaaaaaaaa</b> – aaaaaaaaaa aaaa aaaaaa aa a aaa aa aaaaaa aaa aaaaaaa (aaaaa aaaaaaaa) aaaaaaaa aa aaaaaa aaaaa aaa aaaa</li> </ul> "</string>
uses code from https://github.com/google/bundletool/blob/06296d8ec009af6ec7d09f6da2cf54994fa3a89b/src/main/java/com/android/tools/build/bundletool/model/utils/xmlproto/XmlProtoPrintUtils.java
changed `getHTML()` to use code from …
> fix wrong HTML start/end tags in strings.xml

- brut.apktool/apktool-cli/build.gradle
- brut.apktool/apktool-lib/build.gradle
- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/YamlStringEscapeUtils.java
- build.gradle
A couple of methods of moved to the commons-lang project, so here's a PR to get them from their new home.
> Replace use of deprecated methods with their recommended replacements

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/util/UnknownDirectoryTraversalTest.java
> Cleanup trailing temp files/folders

- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/ClassSafeConstructor.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/EscapedStringRepresenter.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/MetaInfo.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/yaml/MaliciousYamlTest.java
- brut.apktool/apktool-lib/src/test/resources/yaml/cve20220476/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/yaml/cve20220476/apktool.yml
> Preventing instantiation of untrusted classes.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResResSpec.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values/bools.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values/colors.xml
Reverts iBotPeaches/Apktool#2650
> Revert "fix: decoding references to private resources"

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StyledString.java
Fixes #2815 by using recursive writing of nested tags instead of relying on questionable sorting methods.
> fix: redesign StyledString decoding

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java
Fixes ApkTool can't deconstruct apk: https://apkpure.com/facebook/com.facebook.katana
fixes #1719
> Fixes facebook apk deconstruction

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResAttrDecoder.java
* Originally up-streamed by [ljysdfz](https://github.com/ljysdfz) https://github.com/iBotPeaches/Apktool/issues/1361#issuecomment-441691879
* Converted to PR here - https://github.com/iBotPeaches/Apktool/pull/2875
* Duplicated into a PR I can adapt here.
* Fixes https://github.com/iBotPeaches/Apktool/issues/2615
> Support malformed resource names/namespaces by falling back to resId

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
As per the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
> Environment variables: [...] `$XDG_DATA_HOME` defines the base directory relative to which user-specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used. 
Implementing this, makes Apktool work in special environments (such as Flatpak) which by default set XDG_DATA_HOME to something else, without the need to override the path with `--frame-dir`
As far as I know, the BSDs also try to adhere to the XDG spec, so this should be beneficial for them too.
> Make default framework location detection on Linux XDG compliant

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
In case of obfuscated resources, the list of uncompressed files (doNotCompress) is populated with the names of the obfuscated files instead of the names of the decoded files! 
This is a quick fix.
> Fix « doNotCompress » in case of obfuscated resources.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
> fix: support properly mapping r/R/res resources during disassemble

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResResSpec.java
**problem**: If the names of some resources have been deleted, we get an error when building
```bash
W: res/layout/(name removed).xml: Invalid file name: must contain only [a-zA-Z0-9$_.]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)
```
For example, for the [WhatsApp business](https://www.apkmirror.com/apk/whatsapp-inc/whatsapp-business/whatsapp-business-2-22-24-18-release/whatsapp-business-2-22-24-18-2-android-apk-download/)
**reason**: aapt2 return "(name removed)" for deleted resource names
> fix:  res/layout/(name removed).xml: Invalid file name

- brut.apktool/apktool-cli/build.gradle
- brut.apktool/apktool-lib/build.gradle
- brut.j.common/build.gradle
- brut.j.dir/build.gradle
- brut.j.util/build.gradle
- build.gradle
Using Jitpack as a temp service until smali official releases return.
Need to wait 7 days for the artifact to go immutable.
> https://docs.jitpack.io/intro/#immutable-artifacts
---
Fixes #2918
Fixes: #2662
> build: include smali from source

- .github/workflows/build.yml
- gradle/wrapper/gradle-wrapper.properties
* Track older LTS
* Track recent versions
* Fixes #2976
---
So keep 8, 11 and 17 as LTS - then add 18/19 as recent.
> Restructure Testable Java versions.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
> feat: support config flags as low as 8 bytes

- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
Apktool treats APKs with stub resources.arsc like criminals:
```
Exception in thread "main" brut.androlib.AndrolibException: arsc files with zero packages or no arsc file found.
at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:84)
at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
at brut.androlib.Androlib.getResTable(Androlib.java:74)
at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:270)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:110)
at brut.apktool.Main.cmdDecode(Main.java:175)
at brut.apktool.Main.main(Main.java:79)
```
But in fact, those APKs are valid and very common among overlay APKs, but here's a non-overlay example as well:
https://drive.google.com/file/d/1seAnndB9cH6_qo04FC7_1JPW5CVXL …
> fix: accept empty resources.arsc

- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/MetaInfo.java
> fix: support 10mb apktool.yml parsing

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
> fix: properly read 'XML_TYPE_OVERLAY_POLICY'

- .github/CONTRIBUTING.md
- CONTRIBUTORS.md
- brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/mod/SmaliMod.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliBuilder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliDecoder.java
- build.gradle
> Move to official Google smali fork

- brut.apktool/apktool-cli/build.gradle
- settings.gradle
Add application plugin for running from gradle
```bash
.\gradlew run --args="--version"
.\gradlew runShadow --args="--version"
```
> add gradle application plugin to the apktool-cli

- brut.j.util/src/main/java/brut/util/OS.java
Part for correct OS.execAndReturn which always wait 15 seconds, even if the aapt process has been completed successfully
from #3069
> correct always wait 15 seconds

- .github/workflows/build.yml
I keep getting folks reaching out that the build script is vulnerable to x/y/z, despite the "v2" tag being moved/pointed to a non-vulnerable version of these dependencies.
So this should cause their automated scripts to realize no issue and save me having to triage the weekly email about security issues.
> build: lock gradle actions to specific versions

- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/ClassSafeConstructor.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/EscapedStringRepresenter.java
I replaced the deprecated methods in SnakeYAML 1.33 with the respective non-deprecated constructor calls. These are equivalent:
The deprecated non-arg constructor of Constructor https://bitbucket.org/snakeyaml/snakeyaml/src/snakeyaml-1.33/src/main/java/org/yaml/snakeyaml/constructor/Constructor.java calls https://bitbucket.org/snakeyaml/snakeyaml/src/7f5106920d7754ecab734725ba577083e55c7204/src/main/java/org/yaml/snakeyaml/constructor/SafeConstructor.java#lines-52, which uses a new empty LoaderOptions()
Similarly, SafeRepresenter https://bitbucket.org/snakeyaml/snakeyaml/src/7f5106920d7754ecab734725ba577083e55c7204/src/main/java/org/yaml/snakeyaml/representer/SafeRepresenter.java#lines-54 uses a new empty DumperOptions.
> Deprecated SnakeYAML methods

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
1. Rename methods which copy data from decodeXXX to copyXXX
2. Make copy and decode methods private - used from decode()
3. move methods which initialized MetaInfo to the class ResTable
> refactor class ApkDecoder

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
Add common methods decodeManifest and decodeResources.
Remove params wрich duplicates fields
> refactor ApkDecoder - streamline decode procedure

- .github/workflows/build.yml
- .github/workflows/gradle.yml
This is failing quite often when fired off 20~ at once. It doesn't need to be like that. Isolate to its own workflow.
> refactor: put gradle wrapper on its own workflow

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResID.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResAttrDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/XmlPullStreamDecoder.java
* partially reverts https://github.com/iBotPeaches/Apktool/pull/2886
* supersedes https://github.com/iBotPeaches/Apktool/pull/3118
* fixes: #2981 
--- 
Testing #2615 
```
➜  2615 apktool d 2615.apk --only-main-classes -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-7a22af-SNAPSHOT on 2615.apk
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Copying raw assets/39285EFA.dex …
```
> Correct Attribute Resolution

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/arsc/ARSCHeader.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/ProtectedApkTest.java
- brut.j.util/src/main/java/brut/util/ExtDataInput.java
---
This is a major (10yr overdue) refactoring of the core processing of AXML/ARSC in Apktool. This removes the logic that required chunks to be in a specific order as well as revamps chunk loading to handle unknown data reading to survive common obfuscation techniques.
We may have regressed some things, but I'd rather get this merged with the cleaner and more understood codebase and iterate on discovered regressions.
> ARSC/AXML Parser Rework

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
* Skip the locale numbering system as we don't need it.
> Increase known config bytes to 64

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
fixes: #3036 
This cannot be a valid application, but the `entriesCount` seems to be lying. We exceed the chunk size before we are done reading the items. This makes sense in a way because ending the chunk reading when limit is fixed - does correct parsing
However, I am confused how tools like arscblamer, android studio, etc are reading all assets with no skipping of chunks. So perhaps this data is somewhere else, but I'm not sure where. The spec states
https://github.com/aosp-mirror/platform_frameworks_base/blob/main/libs/androidfw/include/androidfw/ResourceTypes.h#L1228
```
// Number of uint32_t entry indices that follow.
uint32_t entryCount;
// Offset from header where ResTable_entry data starts.
uint32_t entriesStart;
```
I've confirmed:
* We are starting reading the entries at …
> fix: skip parsing if chunk end is reached within table chunk

- blog/2016/2016-10-18-release221.mdx
- blog/2017/2017-01-23-release222.mdx
- blog/2017/2017-06-13-release223.mdx
- blog/2017/2017-07-29-release224.mdx
- blog/2017/2017-09-21-release230.mdx
- blog/2017/2017-12-26-release231.mdx
- blog/2018/2018-04-07-release232.mdx
- blog/2018/2018-09-05-release234.mdx
- blog/2019/2019-11-19-release241.mdx
- blog/2020/2020-12-02-release250.mdx
- blog/2021/2021-09-02-release260.mdx
- blog/2022/2022-11-24-release270.mdx
We should let the user be warned they have more frameworks than the default and opt into forced themselves. Just in case there is a situation where folks are caught off-guard by the upgrade guide purging all framework files.
> fix: don't default to --force on upgrade

- brut.j.dir/src/main/java/brut/directory/DirUtil.java
> fix: skip files if cleaned to empty filename

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- build.gradle
fixes: #3174 
fixes: #3170 
* A restriction added to Java and then back-ported to LTS 11 and 17 - https://github.com/openjdk/jdk/commit/fff7e1ad00be07810bf948b8a6f94e83c435fa1f
https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html
> fix: opt out of stricter java rules for zip64 and dot entries

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/ApkInfo.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/yaml/ConsistentPropertyTest.java
- brut.apktool/apktool-lib/src/test/resources/decode/yaml/basic/apktool.yml
> Correct regressions towards apktool.yml generation

- brut.apktool/apktool-cli/build.gradle
- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
In the Idea add gradle execution configuration.
Using:
in the `.gitignore` exists bin/ and out/ directory. Place apk in the bin/ directory and decoding to the out/ directory.
Configuration for decode use Run: `run --args="b -o bin/rebuild.apk out"`
Configuration for build use Run: `run --args="b -o bin/rebuild.apk out"`
In the Main class add printing apk full path if dont find it.
> Allows run app from gradle for debugging purposes

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResAttrDecoder.java
* Superseeds: https://github.com/iBotPeaches/Apktool/pull/3185
* Fixes: #3181
---
In testing I noticed that we were attempting to resolve any value from the resource pool and string pool. This doesn't makes sense all the time for the resource pool for all types. For example, if we got a type float (`0x04`) we'd cast it and shift it to resourceId from the local package. It might/might-not find a resource - thankfully it was always wrong so it didn't win out. It was however inefficient.
> Prevent loading from resource pool if type is not a resolveable resource

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliBuilder.java
- brut.j.util/src/main/java/brut/util/Duo.java
No functional changes, the purpose is to make command descriptions grammatically consistent.
Also removed some redundancy for consistency inside their package.
Added @SuppressWarnings("unchecked") for Duo class to mark the unchecked behavior as intentional.
> style: normalize command descs and redundancy

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
This fixes a regression since 2.8.0 that causes apktool to crash when decompiling framework-res.apk (which has no other framework dependencies):
```
$ java -jar apktool.jar d -f -t mytag framework-res.apk -o framework-res
I: Using Apktool 2.8.1-SNAPSHOT on framework-res.apk
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:247)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:98)
at brut.apktool.Main.cmdDecode(Main.java:190)
at brut.apktool.Main.main(Main.java:93)
```
This is caused by the fact that `mApkInfo.usesFramework` is `null` if …
> fix: crash when decompiling framework-res.apk with a tag (regression)

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values-b+ast+Hant+IT+ARABEXT/strings.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values-b+ast+Latn+IT+AREVELA/strings.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values-b+de+CH+1901/strings.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values-b+iw+660/strings.xml
During operations where we have more bytes than known (Upside down Cake). We improperly leveraged `size` even if we read over that. Additionally had to review some missing support on localeNumbering, which we always skipped.
* https://github.com/aosp-mirror/platform_frameworks_base/blob/9f086e5d7a13df28cc21cc07fadcdb4f2e667258/libs/androidfw/ResourceTypes.cpp#L3028
* http://www.unicode.org/reports/tr35/#UnicodeNumberSystemIdentifier
* https://developer.android.com/guide/topics/resources/providing-resources
> Fix LocaleNumberSystem + ConfigFlag reading

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
Streamline decoding AndroidManifest.xml.
Decoding AndroidManifest.xml without using ResStreamDecoderContainer.
Both methods: decodeManifest decodeManifestWithResources in fact initializes decoder in the same way.
> Streamline decoding AndroidManifest.xml

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
fixes: #1874
In a very old (5+ year) issue. We saw a specific version of Google Hangouts failed to decode. Turns out with some fresh eyes. We just missed an important note in the spec that we should skip entries if the key/offset resolve to -1 (NO_ENTRY)
We applied that to the entry reading as well as the offset reading and it worked great to resolve what used to be this crash:
```
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000202
at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:49)
at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:422)
at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:347)
at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:326)
at …
```
> fix: support skipping entries with NO_ENTRY (-1) flag

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
fixes: #2587 
---
It appears the header size of the start of a namespace entry in this sample is 4 bytes larger than it should. Nothing fills those 4 bytes so it must be either an alignment technique or obfuscation.
> fix: handle larger axml namespace headers than known

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AndroidManifestResourceParser.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResAttrDecoder.java
AXmlResourceParser always set initialized ResAttrDecoder.
Add constructors ResAttrDecoder, AXmlResourceParser(ResTable resTable) and AndroidManifestResourceParser(ResTable resTable) for direct initialization resTable.
> Explicit ResFileDecoder initialization in the decodeResources

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/NonStandardPkgIdTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/DecodeArrayTest.java
Explicit loading restable for support skip resource decoding
> Support explicit operation for when to load full resource table

- scripts/linux/apktool
- scripts/osx/apktool
- scripts/windows/apktool.bat
This is a test upgrade to the helper scripts to see if setting system properties works better than setting them within execution
fixes: #3198
> fix: adjust helper files to include system property sets

- brut.apktool/apktool-lib/src/main/java/brut/androlib/AaptInvoker.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableFalseChangeToTrueTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableTrueAddedTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableTrueRetainedTest.java
Since changing/adapting values or keeping them the same requires continued patches to aapt2. This seems like the best way. We just don't use them.
refs: https://github.com/iBotPeaches/Apktool/discussions/3155
fixes: #3204
> feat: Introduce --no-compile-sdk-metadata

- brut.apktool/apktool-lib/src/test/java/brut/androlib/BaseTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/NetworkConfigTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/NoNetworkConfigTest.java
This should confirm that we no longer modify `platformBuildVersionCode` or `platformBuildVersionName` in aapt2. At the cost of stripping intentionally `compileSdkVersionCodename` and `compileSdkVersion` which I think is fair.
> "--no-compile-sdk-metadata" tests.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
Thanks to the detailed research here: https://github.com/iBotPeaches/Apktool/issues/2070#issuecomment-821853358
It was easy to see that some form of obfuscation (albeit risky) is removing the trailing end-namespace chunks. Since AOSP is smart enough to not read past EOF - it doesn't break on aapt or host.
We now check for the end of file during chunk parsing and jump out early. This should be fine.
---
fixes: #2070
> fix: end parsing if EOF is hit

- .github/workflows/gradle.yml
Resolved the Gradle wrapper validation triggering problem by implementing a more precise check. Now, the validation process will only be triggered when there are actual changes in the gradle/wrapper/gradle-wrapper.jar file, preventing unnecessary validations.
> fix: Gradle wrapper validation trigger issue

- brut.apktool/apktool-lib/src/main/java/org/xmlpull/renamed/MXSerializer.java
In some applications we find duplicate namespaces. This because we move onward to common XML tools to extract/modify end up crashing.
```
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
[Fatal Error] :5:61: Attribute "xmlns:android" was already specified for element "manifest".
```
These were indeed duplicates so it was not Apktool introducing them.
```
➜  2664 aapt2 d xmltree 2664.apk --file AndroidManifest.xml | more
N: android=http://schemas.android.com/apk/res/android (line=4294967295)
N: amazon=http://schemas.amazon.com/apk/res/android (line=4294967295)
N: android=http://schemas.android.com/apk/res/android (line=4294967295)
```
So we maintain a mapping of prefix/uri and skip it if we encounter it again. This happens at …
> fix: support duplicated namespaces

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
In some applications we see the associated namespace is stripped completely.
```
➜  2972 aapt2 dump xmltree base.apk --file AndroidManifest.xml
N: android=http://schemas.android.com/apk/res/android (line=0)
E: manifest (line=0)
A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=23608
A: (0x0101021c)="2.36.8" (Raw: "2.36.8")
A: (0x01010572)=30
A: (0x01010573)="11" (Raw: "11")
A: package="com.bcp.innovacxion.yapeapp" (Raw: "com.bcp.innovacxion.yapeapp")
A: platformBuildVersionCode=30
A: platformBuildVersionName=11
E: uses-sdk (line=0)
A: (0x0101020c)=21
A: (0x01010270)=30
E: supports-screens (line=0)
A: (0x0101026c)=true
A: (0x01010284)=true
A: (0x01010285)=true
A: (0x01010286)=true
A: (0x0101028d)=true
A: (0x010102bf)=true
```
The fix here in theory is easy - resolve …
> fix: resolve missing namespace on system resources

- brut.apktool/apktool-lib/src/test/java/brut/androlib/BaseTest.java
- build.gradle
The old location of XMLUnit has ended. The proper path here is to migrate towards XMLUnit 2.x, but it looks like a challenge to rewrite our XML diff.
For now, a jump to the 2.x port of v1 can gain us an XXE Protection in case malicious test files exist during the build (of apktool). Which honestly I don't think would ever happen as if you have to control of a system that is building apktool itself and have the power to edit/change XML files - you could do more damage.
Part of me also wants to go into a CVE rant about honestly garbage CVEs, but lets upgrade this with 1 line changed to "quiet" some garbage automated scan and be done with this.
> Move to XMLUnit Legacy

- brut.j.dir/src/main/java/brut/directory/DirUtil.java
This adds support to fix disassembly of applications with mega long filenames.
Refs: #3236 
```
➜  3236 apktool d Env145-Vip.apk -s -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.8.2-22eb80-SNAPSHOT on Env145-Vip.apk
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
W: Unknown chunk type at: (0x0000cf18) skipping...
W: AXML hit unexpected end of file at byte: 0xCF18
I: Regular manifest package...
[Fatal Error] :1:1: Premature end of file.
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw …
```
> fix: skip files that attempt to break filesystem

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
fixes: #2824 
In the sample above. We find a duplicate resource at end of chunk.
```
[ResTable_entry] id: 0x0595 name: zero_corner_chip keyIndex: 5176 size: 8 flags: 0x0004
[Res_value] size: 8 dataType: 0x12 data: 0x00000000 ((id))
[ResTable_entry] id: 0x0596 name: zoom keyIndex: 5177 size: 8 flags: 0x0004
[Res_value] size: 8 dataType: 0x12 data: 0x00000000 ((id))
[ResTable_entry] id: 0x0597 name: zoom keyIndex: 5177 size: 8 flags: 0x0004
[Res_value] size: 3 dataType: 0x12 data: 0x00000000 ((id))
```
The last entry has the same index to the previous and malformed. The size reported is also wrong. There are still 8 bytes, but its a duplicate entry.
I've debated a few paths.
* Detecting read vs actual during value read
* Skipping reading if we have less than 8 bytes in value read
In this …
> fix: support decoding application with duplicate res entries

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResPackage.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResResSpec.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTypeSpec.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResScalarValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
First requested by @MrIkso a few years ago in https://github.com/iBotPeaches/Apktool/pull/2463. It was recently broken a few releases back during the sparse resource fixes.
No one really noticed that these were missing and it turns out in a variety of tests - you don't really need them. All they do is bloat codebase, bloat application and unneeded. I may be proven wrong quickly after the removal of this, but since it actually hasn't been working in a year - I think its fair to say no one needs this.
> Remove Apktool Dummys.

- build.gradle.kts
Noticed in https://github.com/iBotPeaches/Apktool/pull/3255 - that shadow was out of date and we could drop the legacy `buildscript` logic for Kotlin DSL plugins.
> build: upgrade to shadow build 8.1.1

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
This is a bit quieter now.
```
I: Using Apktool v2.8.1-41-0e226928-SNAPSHOT on 1407.apk
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Sparsely packed resources detected.
```
Now for chunks we can find out where we crash to easily find the chunk prior to the bad one.
```
FINE: Chunk #70 start: type=0x0202 chunkSize=0x00000030
FINE: Chunk #71 start: type=0x0201 chunkSize=0x000000f4
FINE: Chunk #72 start: type=0x0202 chunkSize=0x00001904
FINE: Chunk #73 start: type=0x3eb0 chunkSize=0x00003ec0
SEVERE: Unknown chunk type: 3eb0
INFO: Decoding file-resources...
````
> Refactor logging for chunks and sparse flags.

- docs/build.mdx
Following the build docs and found that there were a few `*.jar` files the described build folder.
I found that the `apktool-cli-all.jar` file was the one that worked for me whereas the `apk-cli.jar` file returned an error that there was no manifest.
Here, I made the filename a bit more specific so others don't have to test.
Let me know if this is mistaken.
> docs: clarify build file on build doc

- docs/meta/contributing.mdx
Added a little section on fixing detecting and fixing Lint issues when contributing to the documentation.
I've run the Lint check already.
> docs: add lint checking instructions to docs

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
This is to split this out so we can easily unit test it. Intentional obfuscation tricks are proving to be difficult. Where they keep the actual value in the string pool, but spoof an invalid string in the resource table.
> refactor: split out string block vs res table string

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
This appears unused after refactors in: https://github.com/iBotPeaches/Apktool/pull/3217
> refactor: remove unused decodeManifest function

- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/SkipAssetTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/AndResGuardTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/DecodeArrayTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/DecodeKotlinTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/DuplicateDexTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/ExternalEntityTest.java
Removed JUnit deprecations and some extra spaces / unused imports.
> refactor: remove deprecations from test suite

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/SparseFlagTest.java
We have a leaking issue where we populate mApkInfo during each decode, which may be n (each framework). These values are all stored in 1 location. We can prevent setting the sparse flag if we've already loaded the main packages (pkgs within resources.arsc).
fixes: #3298
> Prevent poisioning mResTable if Framework is sparse.

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
This has become way too verbose. I can't even easily grep what I want. Dumping method names just isn't helpful - the helpful log messages that are emitted during verbose is all we need.
prior:
```
Sep 03, 2023 6:19:55 AM brut.androlib.ApkDecoder decode
INFO: Using Apktool v2.8.1-54-06c5f462-SNAPSHOT on Kate.apk
Sep 03, 2023 6:19:55 AM brut.androlib.res.data.ResTable loadMainPkg
INFO: Loading resource table...
Sep 03, 2023 6:19:55 AM brut.androlib.res.decoder.ARSCDecoder readResourceTable
FINE: Chunk #1 start: type=0x0002 chunkSize=0x0010ca40
```
now:
```
I: Using Apktool v2.8.1-54-06c5f462-SNAPSHOT on Kate.apk
F: Chunk #1 start: type=0x0002 chunkSize=0x0010ca40
```
> refactor: verbose doesn't adapt handler

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
fixes: #3311
--
```
F: Chunk #1 start: type=0x0002 chunkSize=0x0002c8fc
F: Chunk #2 start: type=0x0001 chunkSize=0x00010f84
F: Chunk #3 start: type=0x0200 chunkSize=0x0001b96c
F: Chunk #4 start: type=0x0201 chunkSize=0x00003b80
```
The sample included in #3311 is from 2008 Milestone Android builds, which is pre-1.0. Prior to any API stabilization so we can see that they don't have TYPE_SPECS. We can survive disassembly by just making types on the fly if we didn't find one.
> Support Disassembly of mega old Android (M5)

- build.gradle.kts
As reported in XDA - https://forum.xda-developers.com/t/util-jul-22-2023-apktool-tool-for-reverse-engineering-apk-files.1755243/page-305#post-88993197
We somehow broke the compatibility with older Java's. This previously would take the toolchain version of the JDK. Now we enforce 1.8
> fix: enforce java 1.8 compatibility with built artifacts

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
In https://github.com/iBotPeaches/Apktool/pull/3252 we missed a path if the bugged resource was a complex one. This handles that.
> fix: handle duplicate res entries during a complex resource

- brut.apktool/apktool-cli/build.gradle.kts
- brut.apktool/apktool-lib/build.gradle.kts
- brut.j.dir/build.gradle.kts
- brut.j.util/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
This migrates our Kotlin gradle scripts to leverage: https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
This should allow Dependabot to help out again as well as making it clear where our dependency versions are declared.
> build: migrate towards "libs.versions.toml"

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
We will support:
* `resm`
* `res-mode`
* `resolve-resources-mode`
> fix: support more resource-modes params

- .github/workflows/build.yml
This will add support for Dependency Graph uploading - https://github.com/marketplace/actions/gradle-build-action#github-dependency-graph-support
This will allow GitHub to know exact dependencies used, aiding to an easier process with Dependabot and license violation checks, etc.
> build: add dependency graph support

- .github/workflows/docker.yml
- DOCKER.md
- Workflow for building `:<hash>` and `:latest` images and pushing to `ghcr.io` on release
- Updated instructions for `pull`
- Could consider updating to use the locally built JAR in the `build.yml` and including a `:beta` release on PRs into `master` in the future
**NOTE:** I have no real way to test this when integrated into the repo. It is modeled after successful local builds.
> Added auto-build of docker image

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/Config.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/AndroidOreoNotSparseTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/AndroidOreoSparseTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeJarTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/DebugTagRetainedTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/DefaultBaksmaliVariableTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/EmptyResourcesArscTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/ExternalEntityTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/LargeIntsInManifestTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/ProviderAttributeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/SharedLibraryTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/UnknownCompressionTest.java
fixes: #3368 
aapt2 is the default. You can opt back to aapt1 with `--use-aapt1`
> Move aapt2 to default (from aapt1)

- scripts/windows/apktool.bat
A new version of apktool.bat is causing my scripts to fail. For some reason, a .bat ending with `for /f "tokens=x" ...`, when the actual number of tokens is less than expected sets %errorlevel% to '1'. What's funny is that `echo %errorlevel%` prints '0', and even putting `rem` at the end of the file works. Only calling a .bat whose last line is `for /f "tokens=x" ...` from another .bat causes the issue. I had a hard time debugging 😫.
Apart from that, it's just an incorrect way to check for '/c' argument.
> Update Windows helper script to handle /c properly.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/Config.java
The change in PR https://github.com/iBotPeaches/Apktool/pull/3100 made it so `forceApi` was not set anymore. However, the code to build an APK with a specific API level was not updated, causing issues where a newer API level is required.
This PR completely removes `forceApi` and uses the existing `apiLevel` config value.
> use apiLevel instead of forceApi when building the apk

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValue.java
fixes: #3400 
---
We maintain a little set to dedupe attribute names. This can be disabled if analysis mode is enabled.
> feat: de-dupe attribute names during styles writing

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/values/colors.xml
This now decodes into:
```xml
<color name="green_light_gradient">#ff52cb8c</color>
<color name="green_oc831f">@null</color>
<color name="grey">#ffd0cecd</color>
```
Instead of either crashing or becoming an `<item>`
Fixes: #3416
> Adapt null resource to be treated as reference instead of empty string.

- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/res/xml/accessibility_service_config.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/xml/accessibility_service_config.xml
refs: https://github.com/iBotPeaches/Apktool/issues/3425
> test: add test case for android:isAccessibilityTool

- brut.apktool/apktool-lib/src/main/java/brut/androlib/AaptInvoker.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml
```
// Whether validation errors should be treated only as warnings. If this is 'true', then an
// incorrect node will not result in an error, but only as a warning, and the parsing will
// continue.
bool warn_validation = false;
```
Missed this during aapt2 addition. We should have aapt2 in the least strict mode possible as we are rebuilding apps and shouldn't be binded by the latest in build-time enforcement from aapt2.
Fixes: #3427
> #3427 - Treat manifest warnings as warnings

- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/res/values-godzillaui/strings.xml
Was reported that MIUI wasn't working again. This is a simple test to prove yes/no.
> test: assert miui aapt1 patch exists

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/BackgroundWorker.java
- brut.j.dir/src/main/java/brut/directory/ZipUtils.java
Here are my performance optimizations that aim to minimize changes to the codebase and do not use any external libraries (although Apache Compress seems like a nice one).
- There is some duplicated code, such as the ApkBuilder and ApkDecoder new fields, which can be extracted to a "global" context created somewhere in the Main class. However, I do not want to make significant changes for just one pull request.
- I did not find any changes in the decompiled code, compression type issues, or any other problems.
- Further performance optimizations can be done by changing the zip compressing library and refactoring the backsmali code (specifically, the synchronized method inside the library).
**Best numbers (30mb apk, 3 dex files, 4 CPU cores) for a 10-minute benchmark:**
_25% means one core …
> Feature: Parallel Building

- .github/workflows/build.yml
> build(deps): bump actions/upload-artifact from 3 to 4

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
fixes: #3536
Properly handle `stamp-cert-sha256` file as known v3+ signature file. Don't treat as unknown.
> fix: properly handle stamp-cert-sha256

- .github/workflows/build.yml
- brut.apktool/apktool-cli/build.gradle.kts
- brut.apktool/apktool-cli/proguard-rules.pro
- build.gradle.kts
- gradle/libs.versions.toml
In light of recent events - I'm working to prove the builds I make for Apktool are indeed reproducible by the community.
----
> Reproducible Builds

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
Related but unsure if worth separate issues:
- Please add separators between different subcommands. It's really hard to see from the quick glance which options apply to, say, `decode`, especially since they all have different alignment (`if` aligned to 24 columns, `d` to 32, `b` to 25, etc.):
```
usage: apktool [-q|--quiet OR -v|--verbose] if|install-framework [options] <framework.apk>
-p,--frame-path <dir>   Store framework files into <dir>.
-t,--tag <tag>          Tag frameworks using <tag>.
*** Why not put a blank line here? ***
usage: apktool [-q|--quiet OR -v|--verbose] d[ecode] [options] <file_apk>
-api,--api-level <API>         The numeric api-level of the file to generate, e.g. 14 for ICS.
-b,--no-debug-info             Do not write out debug info (.local, .param, .line, etc.)
... …
```
> Correct wording in CLI usage messages

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/Framework.java
If th zip entry for resources.arsc is not found an exception is thrown, but the ZipFile is not closed. Using try-with-resources means that the ZipFile will always be closed irrespective of how the code block exits.
> Resolve a resource leak where the ZipFile is not closed

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
Noticed that when used as a library, you can't delete or rename the manifest file. This fix, should solve the problem.
Here is an example of an error that can happen.
> Add missing stream closing

- brut.j.dir/src/main/java/brut/directory/FileDirectory.java
This lets us assemble classes.dex in a reproducible manner.
Test:
apktool d test.apk > /dev/null
apktool b test > /dev/null
sha1sum test/build/apk/classes.dex
apktool -f d test.apk > /dev/null
apktool b test > /dev/null
sha1sum test/build/apk/classes.dex
> Sort files list in FileDirectory::loadAll()

- scripts/linux/apktool
- scripts/osx/apktool
Similar to the work done on https://github.com/iBotPeaches/Apktool/pull/2120, adding the ability to automatically pick up the latest apktool version for the user.
If the script finds an `apktool.jar` it's selected automatically, otherwise it looks for jar versions available in its directory with the name format `apktool_<version>.jar` and picks the latest accordingly.
> Add ability to automatically pick up the latest apktool.jar version

- brut.apktool/apktool-cli/build.gradle.kts
This fixes 2 things.
```
A problem was found with the configuration of task ':brut.apktool:apktool-cli:shadowJar' (type 'Jar').
- Gradle detected a problem with the following location: 'Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli.jar'.
Reason: Task ':brut.apktool:apktool-cli:generateMetadataFileForMavenJavaPublication' uses this output of task ':brut.apktool:apktool-cli:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
```
Execution failed for task ':brut.apktool:apktool-cli:generateMetadataFileForMavenJavaPublication'.
> java.io.FileNotFoundException: Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli-javadoc.jar (No such file or directory)
```
---
* …
> fix: allow maven to publish without implicit task ordering

- brut.apktool/apktool-lib/src/main/java/android/util/TypedValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/exceptions/CantFind9PatchChunkException.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/exceptions/CantFindFrameworkResException.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/exceptions/InFileNotFoundException.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/exceptions/OutDirExistsException.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/exceptions/UndefinedResObjectException.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java
- brut.apktool/apktool-lib/src/main/java/org/xmlpull/renamed/MXSerializer.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/res/decoder/StringBlockWithSurrogatePairInUtf8Test.java
- brut.j.util/src/main/java/brut/util/OS.java
Clean up tab indentation that snuck during the history of the project.
No other changes.
> style: clean up tab intendation

- brut.apktool/apktool-lib/src/main/java/brut/androlib/AaptInvoker.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/ApkInfo.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/YamlReader.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/YamlWriter.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlPatcher.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/apktool.yml
This records all featureFlag attrs that were enabled when the APK was originally built. This is now required by AAPT2 to pass these flags and their enabled/disabled state if they are used in AndroidManifest.xml.
The flags are recorded to apktool.yml and can be configured, if so desired. In normal usage, all flags should remain set to true (i.e. enabled). Sample APK sourced from AOSP Android 15.
[https://drive.google.com/file/d/1av7Ih7-YUXi73Hf0E3xlPv-V-nE_sXdt/view](https://drive.google.com/file/d/1av7Ih7-YUXi73Hf0E3xlPv-V-nE_sXdt/view)
> new: featureFlags support for SDK 35 apps

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/ApkInfo.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StyledString.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlPatcher.java
- brut.j.dir/src/main/java/brut/directory/FileDirectory.java
Recording feature flags moved to ResourcesDecoder to fix an issue where raw AndroidManifest is attempted to be parsed even when decoding without resources.
Replaced remaining usages of FileInputStream/FileInputStream with their NIO equivalents for consistency with rest of code.
Minor redundancy and format tweaks.
> fix: avoid trying to parse raw AndroidManifest

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlPatcher.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/NetworkConfigTest.java
With `-n` flag:
Current flow: creates a new network_security_config and updates in manifest
Updated flow: check if network_security_config exist, if not, create a new one (current approach) else modify network_security_config to add certificate without losing other rules added by user. i.e whitelisting any domain.
> feat: add user, system certificate in existing network security config

- brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/ApkInfo.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java
* https://developer.android.com/sdk/api_diff/b-dp1/changes
* https://cs.android.com/search?q=baklava&start=1
* https://developer.android.com/about/versions/16
> feat: support for Android Baklava Developer Preview 1

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlUtils.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/BaseTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml
- brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/apktool.yml
Checked aapt2 source and how aapt2 responds to featureFlags specified in tags other than "permission". Apparently it's allowed to appear on any tag inside "manifest" as it's being pre-processed. An easy fix.
Fixes https://github.com/iBotPeaches/Apktool/issues/3768
> fix: support featureFlags anywhere

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.j.util/src/main/java/brut/util/ExtDataInputStream.java
- brut.j.xml/src/main/java/brut/xmlpull/MXSerializer.java
Fixes #3778.
It was noticed that resources were crashing out during disassembly. It seemed a premature exit, but instead the offsets were behind the current location in the stream. Apktool historically had always read entries in order and for the better part of a decade - that worked.
Recently (years ago) obfuscation techniques led Apktool to leveraging a buffered stream alongside a counting stream to properly detect positions in a chunk for skipping, etc. This allowed Apktool to check its current position in order to skip bytes to re-align itself for parsing.
These applications required rewinding the location to the beginning of the chunk so the offset could be properly skipped towards it. So this made a few changes:
* We start a buffered stream as we enter the TYPE chunk (mark)
* If our …
> Fix disassembly of WhatsApp w/ un-ordered resources.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
After https://github.com/iBotPeaches/Apktool/pull/3799 it was determined we exited too early - we should exit after the jumps, in case the elements are out of order and we jump prior to the entire set being read.
fixes: #3778 (again)
> fix: check for oob after jumps in table spec

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlUtils.java
- brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/NetworkConfigTest.java
- brut.apktool/apktool-lib/src/test/resources/aapt2/network_config/res/xml/network_security_config.xml
Handling the case when the network security configs already exist under the `<debug-overrides/>` element.
We should look for the next element under the new element we created/found.
Currently:
```
<network-security-config>
<debug-overrides>
<trust-anchors>
<certificates src="user" />
<certificates src="system" /> --- Added line
</trust-anchors>
</debug-overrides>
<base-config /> --- Added line
</network-security-config>
```
Expected:
```
<network-security-config>
<debug-overrides>
<trust-anchors>
<certificates src="user" />
</trust-anchors>
</debug-overrides>
<base-config>
<trust-anchors>
<certificates src="system" />
<certificates src="user" />
</trust-anchors>
</base-config>
</network-security-config>
```
Example package: `com.tradingview.tradingviewapp`
> fix: update XML element retrieval to use correct parent nodes

- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/arsc/ARSCHeader.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
- brut.j.xml/src/main/java/brut/xmlpull/XmlPullUtils.java
ApkEditor made some improvements which broke Apktool, but kept working on AOSP. Things I saw:
* ApkEditor will make a StringPool chunk and then mislabel the type as something else. So if you are reading the chunk and parse via the type - it'll crash out. This is sneaky because AOSP does not parse any chunks except the one it cares about. So in the situation where AOSP parses `AndroidManifest.xml` it parses ahead (reading header, jumping to end of chunk) until it finds a few elements and in this case `START_ELEMENT`. So when ApkEditor packs bogus chunks of `XML_END_NAMESPACE` and `PACKAGE` Apktool may crash out as it tries to parse those as-is in the middle of an XML node and die.
```java
private void placeBadChunk(AndroidManifestBlock manifestBlock) {
placeBadChunk(manifestBlock, …
```
> Handle another round of "ApkEditor" Protect decoding.

- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
We passed doNotCompress to zipDir as a List.
The longer the list, the slower the lookups.
Convert to a Set for buildApkFile and reuse for all zipDir calls.
> optimize: improve doNotCompress lookups

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResFileValue.java
- brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
Restored the `-api` option for `build` mode for now, and limited opcode API level for `SmaliBuilder` to <= 29.
Realistically, the `-api` option is obsolete for both `decode` and `build` modes, because the process is already automatic and shouldn't be messed with.
All we had to do is limit the opcode API level for `SmaliBuilder` to make sure we assemble dex 039 or older.
dex 040 and 041 don't exist in the wild, and smali assembling for dex 041 is broken for a long time now (writes incomplete header).
> smali: restore -api option and limit to 29

- brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
```
➜  Apktool git:(main) ✗ apktool v
v2.12.1-15-6a0bae60-SNAPSHOT
➜  Apktool git:(main) ✗ apktool version
v2.12.1-15-6a0bae60-SNAPSHOT
➜  Apktool git:(main) ✗ apktool -version
v2.12.1-15-6a0bae60-SNAPSHOT
➜  Apktool git:(main) ✗ apktool --version
v2.12.1-15-6a0bae60-SNAPSHOT
```
> chore: shorten version logic
