iBotPeaches/Apktool

CHANGES
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

- superseeds PR 98 (rscarvalho)

Handles unreadable $HOME gracefully

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java

SPI are not 9patches

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResID.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/SharedLibraryTest.java
brut.apktool/apktool-lib/src/test/resources/brut/apktool/testapp/apktool.yml
brut.apktool/apktool-lib/src/test/resources/brut/apktool/testjar/apktool.yml

- handles references with shared resources
- adds support for --shared-lib
- update unit-tests

Shared Library Rebuilding Support

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java

newFileSystem will file replication overhead

buildUnknownFiles optimization

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.j.util/src/main/java/brut/util/BrutIO.java

`copy` method already in IOUtils

remove BrutIO copy method

---

_data/releases.yml
_layouts/default.html
changes/index.md

Preps documentation for release of `v2.0.0`

Update docs for 2.0.0 Release

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java

fix if size == 28, remainingSize error.

set readConfigFlags read default value to 28

---

brut.j.util/src/main/java/brut/util/OS.java

This will allow to write errors and output to the console handler as usual, but will help to handle errors from external binaries (such as aapt, executed by exec method) in all initialized logger handlers, not only console, but file handler, for ex.

Write output to separate streams (error and output)

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java

Hacky fix FileNotFoundException if file name ends with space

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/Res9patchStreamDecoder.java

	Fix bug reencoding 9patch pngs

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkOptions.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

Support for emptying framework directory.

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java

fix TYPE_DYNAMIC_ATTRIBUTE support

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java

In continue to https://github.com/iBotPeaches/Apktool/pull/1321

show message about null references

---

brut.apktool/apktool-cli/build.gradle
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApktoolProperties.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliBuilder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliDecoder.java
build.gradle

Upgrade to smali 2.2

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliDecoder.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/DefaultBaksmaliVariableTest.java
brut.apktool/apktool-lib/src/test/resources/brut/apktool/issue1481/apktool.yml
brut.apktool/apktool-lib/src/test/resources/brut/apktool/issue1481/smali/com/ibotpeaches/issue1481/BuildConfig.smali

Keep baksmali options same as previous apktool

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.j.dir/src/main/java/brut/directory/AbstractDirectory.java
brut.j.dir/src/main/java/brut/directory/Directory.java
brut.j.dir/src/main/java/brut/directory/ExtFile.java
brut.j.dir/src/main/java/brut/directory/ZipRODirectory.java

This commit should fix https://github.com/iBotPeaches/Apktool/issues/1160

Closing Framework and APK after use

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

Prevent closing objects that may not exist.

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlPatcher.java

Internalize constants to not rely on JDKs

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/xml/ResXmlPatcher.java

Skip JAXP 1.5 features if not on host

---

brut.apktool/apktool-lib/src/test/java/brut/androlib/UnknownDirectoryTraversalTest.java

Detect root file path on windows vs others

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java

Don't read more data than entryChunk has

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java

Survive decoder if malformed string is encountered

---

.travis.yml

rework travis-ci builds

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

- only checks directory path of apktool framework location
- fixes #1586

Refactor directory checks to prevent assumptions

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java

fix potential class cast exceptions

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java

this will just fix some warnings of deprecated API usage, I have noticed during compilation.

update CLI commons API and optimize imports

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

Fix regression when --frame-path points to non existing directory

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java

- missing sample that experiences this
- needs tests
- refs: https://github.com/iBotPeaches/platform_frameworks_base/commit/f90f2f8dc36e7243b85e0b6a7fd5a590893c827e

We are ignoring typeIdOffset

---

brut.j.dir/src/main/java/brut/directory/ZipUtils.java
brut.j.util/src/main/java/brut/util/BrutIO.java

Fix Build Issues on Windows

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkOptions.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/meta/MetaInfo.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResUnknownFiles.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/BaseTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/DoubleExtensionUnknownFileTest.java

Reverting due to issues with implicit sdk versions. See reason why here: https://github.com/iBotPeaches/Apktool/issues/1761#issuecomment-379309998

Revert changes caused by #1272

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.j.dir/src/main/java/brut/directory/Directory.java
brut.j.dir/src/main/java/brut/directory/FileDirectory.java
brut.j.dir/src/main/java/brut/directory/ZipRODirectory.java

This pull request is implementation of the "Suggested solution" in the Description of #1843.

Fix for issue #1843 "APK size increase because of empty file"

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/err/AXmlDecodingException.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/err/RawXmlEncounteredException.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/XmlPullStreamDecoder.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/res/values/public.xml
brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/res/xml/ww_box_styles_schema.xsd
brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/xml/ww_box_styles_schema.xsd

XSD file support for both aapt1/aapt2

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java
brut.j.util/src/main/java/brut/util/ExtDataInput.java

Adapt AXMLResourceParser to handle broken headers.

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java

fix: add headless call in beginning of execution

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

fix: create directory if doesn't exist, before error

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/androlib/InvalidSdkBoundingTest.java

Support for SDK_Q shorthand

---

brut.apktool/apktool-lib/src/main/java/org/xmlpull/renamed/MXSerializer.java

Prevent NPE with missing attributes

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTypeSpec.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResValueFactory.java

Add attr resource type handling

---

.travis.yml
brut.apktool/apktool-cli/build.gradle
build.gradle
scripts/travis-ci/clean-tests.sh
scripts/travis-ci/run-tests.sh

build: test on jdk9 and jdk11

---

brut.apktool/apktool-lib/src/test/java/brut/androlib/util/UnknownDirectoryTraversalTest.java
brut.j.dir/src/main/java/brut/directory/DirUtil.java

Supersedes: https://github.com/iBotPeaches/Apktool/pull/2058

Issue 2058

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/src/SmaliDecoder.java
build.gradle
scripts/travis-ci/clean-tests.sh
scripts/travis-ci/run-tests.sh

Update to smali/baksmali v2.3.0

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

bugfix: selectPkgWithMostResSpecs return wrong pkg, please review ASAP. @iBotPeaches

bugfix, fix get wrong package ResPackage for multi-pkg resources.arsc.

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java

jerry@jerry-B85M-D3V-A:~/yun_package$ java -jar apktool-cli-all.jar d --only-main-classes sign_50805_1112.apk
Unrecognized option: --only-main-classes
............
............

fix bug of Unrecognized option: --only-main-classes

---

brut.j.util/src/main/java/brut/util/OSDetection.java

fix: enhance bitness detection on windows

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

supersedes: https://github.com/iBotPeaches/Apktool/pull/2192
fixes: #1272

Support file with do-not-compress entries

---

install/index.md

Added instruction for Homebrew installation (macOS only)

Add instruction for Homebrew installation

---

brut.j.util/src/main/java/brut/util/Jar.java

fix issue-2251

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

fix: put the resources.arsc file under STORED compression into framework

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/XmlPullStreamDecoder.java

fixes: https://github.com/iBotPeaches/Apktool/issues/2368

fix: prevent nullying out sdk info when compileSdkVersion is found

---

brut.apktool/apktool-cli/build.gradle
brut.apktool/apktool-lib/build.gradle
brut.j.common/build.gradle
brut.j.dir/build.gradle
brut.j.util/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Changes:
* Updated Gradle from 6.4.1 to 6.5.1
* Updated shadow from 5.1.0 to 6.0.0
* Updated proguard from 6.1.1 to 7.0.0
* Changed 'compile' configuration with proper 'implementation' and 'api' configurations

Various gradle files updates

---

contribute/index.md

The CONTRIBUTING.md file was moved to .github/ : https://github.com/iBotPeaches/Apktool/commit/a7535f36d93893bd422169775610b52fc4db7b75

Update CONTRIBUTING.md link

---

brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/BuildAndDecodeTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/smali_classes3/HelloTripleDexSupport.smali
brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/smali/HelloWorld.smali
brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/smali_classes2/HelloDualDexSupport.smali
brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/smali_classes3/HelloTripleDexSupport.smali

The aapt version is not really related, but I don't have a split test case for just generic source file tests. 
Fixes: #2411

Single/Dual/Triple classes# dex file test (aapt1/aapt2)

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

fix: add better error message when can't write framework file

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java

fix: add message explaining deprecation of 32bit

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResEnumAttr.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResFlagsAttr.java

fix NPE when finding a null referent

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

Feat: List Frameworks

---

brut.j.util/src/main/java/brut/util/OS.java

fix: early return if no files + enhanced for loop

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResResSpec.java

fix: rename duplicate attributes to not start with numeric

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.j.dir/src/main/java/brut/directory/DirUtil.java
brut.j.util/src/main/java/brut/util/BrutIO.java

Issue 2201 - Skip files that violate safe filepath

---

brut.j.dir/src/main/java/brut/directory/AbstractDirectory.java
brut.j.dir/src/main/java/brut/directory/DirUtil.java
brut.j.dir/src/main/java/brut/directory/ZipUtils.java
brut.j.util/src/main/java/brut/util/DataInputDelegate.java
brut.j.util/src/main/java/brut/util/Jar.java
brut.j.util/src/main/java/brut/util/OS.java
brut.j.util/src/main/java/brut/util/OSDetection.java

I have corrected some code smell
- Correct use of <> diamond operator
- Correct modifiers order
- Private constructor for some utility class
- Correct use of diamond operator
- Corrected naming convention
- Correct modifier order
- Use not synchronized class
- Introduced try/resource in stream copy
- Removed unused private field 
I hope this may be usefull for Apktool

Code smell reduction

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResScalarValue.java

fix: write dummy resources as items

---

.editorconfig
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Update dependencies
- Add `.editorconfig` for format

Update dependencies & Add .editorconfig

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStringValue.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AndroidManifestResourceParser.java
brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/AndroidManifest.xml
brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml

Fix: numeric string meta-data value corruption

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/options/BuildOptions.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResTable.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/TestUtils.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/AndroidOreoNotSparseTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/AndroidOreoSparseTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/DebugTagRetainedTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/EmptyResourcesArscTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/SharedLibraryTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt1/UnknownCompressionTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/BuildAndDecodeTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableFalseChangeToTrueTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableTrueAddedTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/DebuggableTrueRetainedTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/aapt2/NonStandardPkgIdTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/DuplicateDexTest.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/res/src/DexStaticFieldValueTest.java

This moves the Build options into a new location to prepare for DecodeOptions

Begin options refactor

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java

fix: support for signature scheme v4

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java

fix: prevent file hold on tmpDir during build

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java

feat: introduce SDK_S_V2

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java

fix: properly release resource

---

brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml

test (aapt2): add assertion for "usesPermissionFlags"

---

.github/workflows/build.yml
brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/AndroidManifest.xml
brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml

test (aapt/aapt2): ensure ampersand is escaped on android:label

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java

Succeeds https://github.com/iBotPeaches/Apktool/pull/2885 so I can push commits.
Closes: #2885

Support Spare Flags

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AndroidManifestResourceParser.java

fix: correct npe if null is returned from attribute value

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java

fix: overlay spec parsing (#2805)

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResEnumAttr.java

fix: don't assume a referent exists on ReferenceValue

---

scripts/windows/apktool.bat

Reverts iBotPeaches/Apktool#2930

Revert "Update apktool.bat"

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/Androlib.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/decode/AndResGuardTest.java
brut.j.dir/src/main/java/brut/directory/DirUtil.java

Issue 2943 - Support raw disassembly w/ AndResGuard

---

brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml

fixes: https://github.com/iBotPeaches/Apktool/issues/3041

feat: update internal framework to API 34 (Upside Down Cake Preview)

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResResSpec.java

fix: support `0_resource_name_obfuscated`

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java

fix: handle invalid string id during namespace resolution

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/ResConfigFlags.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/androlib/InvalidSdkBoundingTest.java

feat: support upside-down-cake/vanilla-ice-cream sdk shorthand

---

docusaurus.config.js
package-lock.json
package.json

Keep our old links redirecting

feat: redirect old links to new

---

docs/meta/contributing.mdx
docs/meta/pitch.mdx
docusaurus.config.js

feat: add Contributing page

---

docs/meta/pitch.mdx

Got another message how Apktool compares to apkanalyzer.

docs: call out apkanalyzer

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/AXmlResourceParser.java

fix: skip unknown chunks in AXML

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StyledString.java

fix: support encode styled string if length larger than offset

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/StringBlock.java

Much like we did in the ARSC and AXML parsers.

refactor: change naming pattern of class variables in StringBlock

---

scripts/linux/apktool
scripts/osx/apktool
scripts/windows/apktool.bat

fix: bump heap size to 1g max

---

.github/workflows/build.yml

fix: correct path to archive during ci

---

.github/workflows/build.yml
brut.apktool/apktool-cli/build.gradle.kts

feat: shorten archive name to apktool-{version}.jar

---

.github/workflows/build.yml

fix: obtain git history for proper "git describe"

---

.github/workflows/docker-beta.yml
.github/workflows/docker-release.yml

refactor: hard-code IMAGE_NAME, add some spaces

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ARSCDecoder.java

This will help quickly jump to the chunk under investigation.

refactor: support current position during chunk verbose output

---

.github/workflows/docker-beta.yml
.github/workflows/docker-release.yml

build: docker fixes

---

README.md

Changed the README description part, to improve clarity, changed some "It' to "Apktool", and some general grammatical improvements.

chore: minor clarity improvement in README.md

---

brut.apktool/apktool-lib/src/main/java/org/xmlpull/renamed/MXSerializer.java

Correct Facebook Disassembly (Jan 2024)

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkDecoder.java

fix: properly record compression of non-main classes.dex files

---

brut.apktool/apktool-cli/build.gradle.kts
brut.apktool/apktool-cli/proguard-rules.pro
build.gradle.kts
gradle/libs.versions.toml

Workaround invalid org.xmlpull loader with R8

---

README.md

Hi @iBotPeaches I've improved this commit and added the second commit you requested to sync with the documentation readme.
---
Squashed from #3598
Requires: #3610

Readme: Improve title and wording for docs link

---

README.md

(docs) Readme: Improve title and wording for main tool link (#3611)

---

brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/AndroidManifest.xml

test(aapt2) - add foregroundServiceType test

---

brut.apktool/apktool-lib/src/main/java/brut/androlib/AaptInvoker.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/apk/ApkInfo.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/Framework.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResFileDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/decoder/ResRawStreamDecoder.java
brut.j.dir/src/main/java/brut/directory/DirUtil.java
brut.j.util/src/main/java/brut/util/BrutIO.java
brut.j.util/src/main/java/brut/util/ExtCountingDataInput.java
brut.j.util/src/main/java/brut/util/Jar.java
brut.j.util/src/main/java/brut/util/OS.java

Use BrutIO where possible to improve and simplify stream handling. Ensure streams are closed when no longer needed.
Some minor formatting tweaks and naming consistency.
No functionality changes.

refactor: tweaks IO handling

---

README.md

docs: update readme for doc repo move

---

brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AaptInvoker.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AaptManager.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/ResourcesDecoder.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/table/value/ResAttribute.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/table/value/ResEnum.java
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/table/value/ResFlags.java
brut.apktool/apktool-lib/src/test/java/brut/androlib/res/AaptVersionTest.java

organize: classes by context

---

INTERNAL.md

Fix: correct bad Windows aapt2 builds
